apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: kamalfarah/hello-world:9
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001  # Accessible via minikube ip:30001
